environment:
  matrix:
    - RUST: nightly
      BITS: 32
    - RUST: nightly
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-gnu.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
  - ps: Start-FileDownload $Env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Gcc,Cargo,Std" /DIR="C:\Rust"
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose
  - cargo test --verbose
